PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ofxsTransform3x3.o ofxsTransformInteract.o ofxsShutter.o Transform.o
PLUGINNAME = Transform
RESOURCES = net.sf.openfx.MzTransformMaskedPlugin.png net.sf.openfx.MzTransformPlugin.png net.sf.openfx.MzTransformMaskedPlugin.svg net.sf.openfx.MzTransformPlugin.svg net.sf.openfx.MzDirBlur.png net.sf.openfx.MzDirBlur.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
