PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ofxsTransform3x3.o ofxsOGLTextRenderer.o ofxsOGLFontData.o ofxsShutter.o CornerPin.o
PLUGINNAME = CornerPin
RESOURCES = net.sf.openfx.MzCornerPinMaskedPlugin.png net.sf.openfx.MzCornerPinPlugin.png net.sf.openfx.MzCornerPinMaskedPlugin.svg net.sf.openfx.MzCornerPinPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
