PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o Position.o ofxsOGLTextRenderer.o ofxsOGLFontData.o
PLUGINNAME = Position
RESOURCES = net.sf.openfx.MzPosition.png net.sf.openfx.MzPosition.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
